name: kinetic_sdk
version: 1.0.0-rc.13
description: The official Kinetic SDK
homepage: https://github.com/kinnytips/kinetic-dart-sdk
repository: https://github.com/kinnytips/kinetic-dart-sdk
issue_tracker: https://github.com/kinnytips/kinetic-dart-sdk/issues
documentation: https://kinny.io/docs/developers/flutter-dart

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.6
  bs58: ^1.0.2
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  meta: ^1.9.1
  solana: ^0.30.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

