name: Dart Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Dart
      uses: nikosportolos/dart_package@v0.2.1
      with:
        sdk: 'stable'

    - name: Install dependencies
      run: dart pub get

    - name: Run tests
      run: dart test

    - name: Publish to pub.dev (dry run)
      env:
        PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
      run: dart pub publish --dry-run

    - name: Publish to pub.dev
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOK
