name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setting up the Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Analyze the project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      - name: dart-package
        uses: nikosportolos/dart_package@v0.2.1
        with:
          coverage: true
          codecov: true
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          publish: true
          pubdev_token: ${{ secrets.PUBDEV_TOKEN }}
          sdk: flutter
          flutter-sdk: '3.13.8'
